services:
  mysql-m:
    image: mysql:latest
    container_name: mysql-m
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db
    ports:
      - "3310:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW
    networks:
      - mysql-net



  mysql-s1:
    image: mysql:latest
    container_name: mysql-s1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3311:3306"
    command: --server-id=2 --relay-log=relay-bin
    depends_on:
      - mysql-m
    networks:
      - mysql-net

  mysql-s2:
    image: mysql:latest
    container_name: mysql-s2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3312:3306"
    command: --server-id=3 --relay-log=relay-bin
    depends_on:
      - mysql-m
    networks:
      - mysql-net

networks:
  mysql-net:
    driver: bridge